import type {Metadata} from "next";
import {Roboto_Slab} from "next/font/google";
import "./globals.css";


const roboto_slab = Roboto_Slab({
    variable: "--font-roboto-slab",
    subsets: ['latin']
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${roboto_slab.variable}  antialiased`}
        >

        {children}
        </body>
        </html>
    );
}
